#!/usr/bin/env bash
# Bash script that generates a MySQL dump

password=$1
name_backup=$(date +%d-%m-%Y).tar.gz
#Backup
mysqldump --all-databases -u root –p "$password" > backup.sql
#creates a tar.gz archive
tar -czvf "$name_backup" backup.sql
