#!/usr/bin/env bash
#Requirement: Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
#Bug: netstat -lpn does not show port 80

#rm /etc/nginx/sites-enabled/default
#ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#sudo service nginx restart

sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart