#!/usr/bin/env bash
# script to link sites-enabled to sites-available and & create a zombie process
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
kill -9 "$(cat /var/run/nginx.pid)"