#!/usr/bin/env bash
# -nginx must be running as nginx user
# -nginx must be listening on all active IPs on port 8080
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf

# update nginx file to listen to 8080
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default

# netstat -lpn shows apache2 is using 8080
pkill apache2
sudo -u nginx service nginx stop
sudo -u nginx service nginx start